### ISSUE TITLE
Observation shapes do not match

### ISSUE THREAD

**Issue by parthjaggi** [kandouss/marlgrid#4]
```
env = gym.make('MarlGrid-2AgentEmpty9x9-v0')

act = env.action_space.sample()
obs, rew, done, _ = env.step(act)
obs = np.array(obs)
```
`obs.shape` gives me `(2, 56, 56, 3)`, while `env.observation_shape` gives me `Tuple(Box(7, 7, 3), Box(7, 7, 3))`.
Mismatch between the two.

**Comment by kandouss** [comment]
Just saw this now :)
Good catch! Updated with a quick fix.
